#!/bin/sh
#

# import run environment
source /etc/run.env

# Add SMACK netlabel and ipv6host exceptions to grant applications
# permission to communicate with the Internet via IPv4 and IPv6.
# Reference: kernel.org smack admin-guide.
add_system_smack_exceptions()
{
    local smack_net_label=/sys/fs/smackfs/netlabel
    local smack_ipv6_host=/sys/fs/smackfs/ipv6host
    # !TODO: Allow only a specific label. (Need change in Legato as well).
    local single_label="@" # internet, access to all.
    local host_ip="0.0.0.0/0" # all
    local host_ip6="0:0:0:0:0:0:0:0/0" # all

    # netlabel exceptions
    local rule="127.0.0.1 -CIPSO"
    echo "${rule}" > ${smack_net_label}
    if [ $? -ne 0 ]; then
        echo "${this_e}: Error loading system SMACK netlabel exception: ${rule}."
        return ${SWI_ERR}
    fi
    rule="${host_ip} ${single_label}"
    echo "${rule}" > ${smack_net_label}
    if [ $? -ne 0 ]; then
        echo "${this_e}: Error loading system SMACK netlabel exception: ${rule}."
        return ${SWI_ERR}
    fi

    # IPv6 host exceptions
    rule="${host_ip6} ${single_label}"
    echo "${rule}" > ${smack_ipv6_host}
    if [ $? -ne 0 ]; then
        echo "${this_e}: Error loading system SMACK IPv6 host exception: ${rule}."
        return ${SWI_ERR}
    fi
}

# Add SMACK rules considered to be system related.
# All the rules must be located in /etc/smack/accesses, because
# we could also use smack userland tools to load the rules from
# this file (if we choose to do so later on).
add_system_smack_rules()
{
    local smack_rules_src=/etc/smack/accesses
    local smack_rules_dst=/sys/fs/smackfs/load2
    local smack_delay=
    local ret=${SWI_OK}

    if [ ! -f ${smack_rules_src} ] ; then
        echo "${this_e}: Cannot find ${smack_rules_src}."
        return ${SWI_ERR}
    fi

    if [ ! -f ${smack_rules_dst} ] ; then
        echo "${this_e}: Cannot find ${smack_rules_dst}."
        return ${SWI_ERR}
    fi

    (   set -e; \
        while read -r -u 10 i; do \
            if ! echo "$i" | grep -q -e '^#' -e '^ *$'; then \
                if echo $i; then \
                    sleep ${smack_delay:-0}; \
                else \
                    echo "${this_e}: Invalid line in ${smack_rules_src}: $i" >&2; \
                    return ${SWI_ERR}; \
                fi; \
            fi; \
        done ) 10<${smack_rules_src} >${smack_rules_dst}
    if [ $? -ne 0 ]; then
        echo "${this_e}: Error loading system SMACK rules."
        ret=${SWI_ERR}
    fi

    return ${ret}
}

#
# Execution starts here.
#
case "$1" in
    start)
        add_system_smack_exceptions
        if [ $? -ne 0 ] ; then
            echo "${this_e}: Failed to add system SMACK exceptions."
            umount /sys/fs/smackfs >/dev/null 2>&1
        fi
        add_system_smack_rules
        if [ $? -ne 0 ] ; then
            echo "${this_e}: Failed to add system SMACK rules."
            exit 1
        fi
    ;;

    stop)
    ;;

    *)
        echo "Usage: ${this_e} {start | stop}"
        exit 1
    ;;
esac

exit 0

