#!/bin/sh
### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Dropbear Secure Shell server
### END INIT INFO
#
# Do not configure this file. Edit /etc/default/dropbear instead!
#
# Import run environment
source /etc/run.env

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dropbear
NAME=dropbear
DESC="Dropbear SSH server"
PIDFILE=/var/run/dropbear.pid

DROPBEAR_PORT=22
DROPBEAR_EXTRA_ARGS=
NO_START=0
KEYS_PATH="/etc/dropbear"

set -e

test ! -r /etc/default/dropbear || . /etc/default/dropbear
test "$NO_START" = "0" || exit 0
test -x "$DAEMON" || exit 0
test ! -h /var/service/dropbear || exit 0

DROPBEAR_RSAKEY_DEFAULT="${KEYS_PATH}/dropbear_rsa_host_key"

# Check if /etc overlay is mounted. If no, /etc is assumed R/O.
if ! is_etc_writable; then
    if is_flash_mountpoint_writable; then
        KEYS_PATH="${FLASH_MOUNTPOINT_RFS}/etc/dropbear"
    else
        KEYS_PATH="/tmp/rootfs/etc/dropbear"
    fi
    mkdir -p ${KEYS_PATH}
    DROPBEAR_RSAKEY_DEFAULT=${KEYS_PATH}/dropbear_rsa_host_key
    DROPBEAR_DSSKEY_DEFAULT=${KEYS_PATH}/dropbear_dss_host_key
fi

test -z "$DROPBEAR_BANNER" || \
  DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -b $DROPBEAR_BANNER"
test -n "$DROPBEAR_RSAKEY" || \
  DROPBEAR_RSAKEY=$DROPBEAR_RSAKEY_DEFAULT

gen_keys() {
    if [ -f "$DROPBEAR_RSAKEY" -a ! -s "$DROPBEAR_RSAKEY" ]; then
        rm $DROPBEAR_RSAKEY || true
    fi
    test -f $DROPBEAR_RSAKEY || dropbearkey -t rsa -f $DROPBEAR_RSAKEY $DROPBEAR_RSAKEY_ARGS
}

case "$1" in
  start)
	echo -n "Starting $DESC: "
	gen_keys
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- -r $DROPBEAR_RSAKEY \
	    -p "$DROPBEAR_PORT" $DROPBEAR_EXTRA_ARGS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	sleep 1
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- -r $DROPBEAR_RSAKEY \
	    -p "$DROPBEAR_PORT" $DROPBEAR_EXTRA_ARGS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
