#! /bin/sh
# Copyright (c) 2019-2020, The Linux Foundation. All rights reserved.
# Modified by Dragan Marinkovic <dmarinkovi@sierrawireless.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
        echo -n "Starting/Loading audio module: "

        echo "audio:start/load" > /dev/kmsg
        insmod $MODULE_BASE/extra/apr_dlkm.ko
        insmod $MODULE_BASE/extra/adsp_loader_dlkm.ko
        echo 1 > /sys/kernel/boot_adsp/boot
        insmod $MODULE_BASE/extra/q6_dlkm.ko
        insmod $MODULE_BASE/extra/platform_dlkm.ko
        insmod $MODULE_BASE/extra/stub_dlkm.ko
        insmod $MODULE_BASE/extra/wcd_core_dlkm.ko
        insmod $MODULE_BASE/extra/wcd_cpe_dlkm.ko
        insmod $MODULE_BASE/extra/wcd9330_dlkm.ko
        insmod $MODULE_BASE/extra/wm8944_dlkm.ko
        insmod $MODULE_BASE/extra/machine_dlkm.ko

        echo "done loading audio_kernel module"
        ;;
  stop)
        echo "Unloading audio_kernel modules " > /dev/kmsg
        rmmod machine_dlkm
        rmmod wm8944_dlkm
        rmmod wcd9330_dlkm
        rmmod wcd_cpe_dlkm
        rmmod wcd_core_dlkm
        rmmod stub_dlkm
        rmmod platform_dlkm
        rmmod q6_dlkm
        echo "audio: unvoting for adsp" > /dev/kmsg
        echo 0 > /sys/kernel/boot_adsp/boot
        echo "Unloading adsp_loader and apr" > /dev/kmsg
        rmmod adsp_loader_dlkm
        rmmod apr_dlkm
        echo "Unloading audio_kernel modules completed" > /dev/kmsg
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
