#!/bin/sh
#
# Copyright (c) 2013, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE DISCLAIMED.  IN NO
# EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DESCRIPTION:  DIAG+ADB+ECM

echo "Switching to composition sierra_dev (1199:68C0)"

if [ "x$1" = "xy" ]; then
        num="1"
        mode="hsic"
else
        num="0"
        mode="hsusb"
fi

vid=$(/usr/bin/ud_getusbinfo VID)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets VID failed"
  vid=1199
fi

pid=$(/usr/bin/ud_getusbinfo PID)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets PID failed"
  pid=68C0
fi

devclass=$(/usr/bin/ud_getusbinfo DEVC)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets DEVC failed"
  devclass=239
fi

devsubclass=$(/usr/bin/ud_getusbinfo DEVS)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets DEVS failed"
  devsubclass=2
fi

devprotocol=$(/usr/bin/ud_getusbinfo DEVP)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets DEVP failed"
  devprotocol=1
fi

diagstr=$(/usr/bin/ud_getusbinfo DIAGSTR)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets DIAGSTR failed"
  diagstr='diag'
fi

serialstr=$(/usr/bin/ud_getusbinfo SERIALSTR)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets SERIALSTR failed"
  serialstr='smd,tty'
fi

compstr=$(/usr/bin/ud_getusbinfo COMPSTR)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets COMPSTR failed"
  compstr='diag,ffs,serial'
fi

remotewakeup=$(/usr/bin/ud_getusbinfo REM)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets REM failed"
  remotewakeup=1
fi

manufacturer=$(/usr/bin/ud_getusbinfo MANU)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets MANU failed"
  manufacturer='Sierra Wireless, Incorporated'
fi

product=$(/usr/bin/ud_getusbinfo PROD)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets PROD failed"
  product='AR758x'
fi

serial=$(/usr/bin/ud_getusbinfo SER)
if [ $? -ne 0 ];
then
  echo "ud_getusbinfo gets SER failed"
  serial='0123456789ABCDEF'
fi

#echo $mode > /sys/bus/platform/devices/usb_bam/enable
echo 0 > /sys/class/android_usb/android$num/enable
echo $vid > /sys/class/android_usb/android$num/idVendor
echo $pid > /sys/class/android_usb/android$num/idProduct
echo $devclass > /sys/class/android_usb/android$num/bDeviceClass
echo $devsubclass > /sys/class/android_usb/android$num/bDeviceSubClass
echo $devprotocol > /sys/class/android_usb/android$num/bDeviceProtocol
echo $diagstr > /sys/class/android_usb/android$num/f_diag/clients
echo $serialstr > /sys/class/android_usb/android$num/f_serial/transports
echo QTI,BAM_DMUX > /sys/class/android_usb/android$num/f_rmnet/transports
echo $compstr > /sys/class/android_usb/android$num/functions
echo $remotewakeup > /sys/class/android_usb/android$num/remote_wakeup

echo $manufacturer > /sys/class/android_usb/android$num/iManufacturer
echo $product > /sys/class/android_usb/android$num/iProduct
echo $serial > /sys/class/android_usb/android$num/iSerial

compstr=`grep -w ffs /sys/class/android_usb/android0/functions || true`
if [[ $mode = "hsusb" && ! -z "$compstr" && -d /sys/class/android_usb/android0/f_ffs ]] ; then
    echo adb > /sys/class/android_usb/android0/f_ffs/aliases
fi

echo 1 > /sys/class/android_usb/android$num/enable


