#! /bin/sh

set -e

case "$1" in
  start)
    echo -n "Starting reboot daemon: "
    start-stop-daemon -S -b -a /sbin/reboot-daemon
    echo "done"
    ;;
  stop)
    echo -n "Stopping reboot daemon: "
    start-stop-daemon -K -n reboot-daemon
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage rebootdaemon { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
